ome/ome-model

- specification/samples/2016-06/ROI.ome.xml
Insight doesn't appear to apply the transform, which is a simple translation.  It validates, but is it correct?
> samples: Add Transform example to ROI sample

- ome-xml/pom.xml
- pom.xml
- specification/pom.xml
Following https://github.com/ome/ome-model/pull/16,
- Remove `pluginRepositories` section already defined in the [Super POM](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Super_POM)
- Clean up the module POMs
> Additional POM cleanup

- docs/sphinx/conf.py
- docs/sphinx/developers/index.rst
- docs/sphinx/ome-tiff/code.rst
- docs/sphinx/ome-xml/java-library.rst
Testing: Check edit on github links; should use the master branch.
See http://www.openmicroscopy.org/site/support/ome-files-cpp-staging/ome-model/manual/html/index.html
> docs: sphinx: Use master as the source branch

- CMakeLists.txt
- cmake/FindBoost.cmake
See https://github.com/ome/ome-cmake-superbuild/pull/159 for testing instructions.
> cmake: FindBoost requires cmake 3.4

- CMakeLists.txt
- cmake/BoostChecks.cmake
- cmake/CompilerChecks.cmake
- cmake/Doxygen.cmake
- cmake/DoxygenCheck.cmake
- cmake/GTest.cmake
- cmake/HeaderTest.cmake
- cmake/PlatformChecks.cmake
- cmake/RegexChecks.cmake
- cmake/ThreadChecks.cmake
- cmake/XalanChecks.cmake
- cmake/XercesChecks.cmake
- cmake/XsdFu.cmake
- docs/doxygen/CMakeLists.txt
- ome-xml/CMakeLists.txt
- ome-xml/src/main/cpp/CMakeLists.txt
- ome-xml/src/main/cpp/ome/test/CMakeLists.txt
- ome-xml/src/main/cpp/ome/test/io.cpp
- ome-xml/src/main/cpp/ome/test/main.cpp
- ome-xml/src/main/cpp/ome/xml/CMakeLists.txt
- ome-xml/src/main/cpp/ome/xml/OMEEntityResolver.h
- ome-xml/src/main/cpp/ome/xml/OMETransform.h
- ome-xml/src/test/cpp/CMakeLists.txt
See https://github.com/ome/ome-common-cpp/pull/46
> Use C++11 <thread> and <mutex>

- cmake/BoostChecks.cmake
- docs/doxygen/ome-xml.dox.cmake
- ome-xml/src/main/cpp/ome/xml/model/OriginalMetadataAnnotation.cpp
- xsd-fu/templates-cpp/OMEXMLModelObject.template
See https://trello.com/c/YJBB1cOA/11-centos-7-platform-support
Not for merging at this point.
> Boost 1.53 revert

- docs/sphinx/ome-tiff/tools.rst
See https://ci.openmicroscopy.org/view/Failing/job/OME-FILES-CPP-DEV-merge-docs/BUILD_TYPE=Release,node=marlin/506/console
This link was breaking the build and was actually broken, new link should fix things.
> Fix XML-LibXML link

- docs/sphinx/conf.py
- docs/sphinx/ome-tiff/index.rst
Attempt to fix https://ci.openmicroscopy.org/job/MODEL-merge-docs/329/
> Use HTTPS for Leica Microsystems URL

- NEWS.md
- ome-xml/src/main/java/ome/xml/model/primitives/NonNegativeFloat.java
- ome-xml/src/main/java/ome/xml/model/primitives/NonNegativeInteger.java
- ome-xml/src/main/java/ome/xml/model/primitives/NonNegativeLong.java
- ome-xml/src/main/java/ome/xml/model/primitives/PercentFraction.java
- ome-xml/src/main/java/ome/xml/model/primitives/PositiveFloat.java
- ome-xml/src/main/java/ome/xml/model/primitives/PositiveInteger.java
- ome-xml/src/main/java/ome/xml/model/primitives/PositiveLong.java
This PR simply changes the wording of some numerical exceptions' messages. My intent is to make the meaning clearer at first glance. When I first read https://www.openmicroscopy.org/qa2/qa/feedback/19174/ I was kind of nonplussed.
> reword value domain constraint error messages

- docs/sphinx/conf.py
Implements solution from https://github.com/openmicroscopy/ome-internal/pull/381 to improve the linkchecker
> Improve linkchecker

- .appveyor.yml
- .travis.yml
- docs/sphinx/pom.xml
- pom.xml
See https://github.com/ome/bio-formats-build/pull/22
> Build updates

- ome_model/experimental.py
See http://lists.openmicroscopy.org.uk/pipermail/ome-users/2018-November/007281.html
This builds on top of #91 to create companion OME-XML for SPW use cases.
> Expand experimental model library to generate SPW samples

- ome_model/experimental.py
Propose to get this out as 6.0.0a2 today.
cc: @sbesson
> Minor py fixes

- .travis.yml
- requirements.txt
Attempts to fix the documentation jobs by uncapping this Sphinx version.
> Sphinx & Python 3

- docs/sphinx/ome-tiff/data.rst
See https://ci.openmicroscopy.org/job/MODEL-merge-docs/ws/src/docs/sphinx/target/sphinx/html/ome-tiff/data.html#d-datasets once logged into Jenkins master. [MODEL-merge-docs](https://ci.openmicroscopy.org/job/MODEL-merge-docs/) should return to passing.
> Fix docs link to Josh Bembenek page.

- docs/sphinx/ome-tiff/data.rst
- docs/sphinx/ome-tiff/index.rst
* LOCI's WiscScan software
* GE Healthcare now largely Cytiva.
> Fix doc hyperlinks to follow external site changes.

- docs/sphinx/conf.py
- docs/sphinx/ome-tiff/data.rst
- docs/sphinx/ome-tiff/index.rst
While reviewing #113 I figured this might speed up the linkcheck process
> Fix a few HTTP -> HTTPS redirections

- docs/sphinx/ome-tiff/data.rst
Documents the new multi-file OME-TIFF sample
> Add companion plate to the sample OME-TIFF page

- docs/sphinx/ome-tiff/tools.rst
point to a validator now that the previous one is gone
I picked a W3C XML Schema (XSD) Validation online 
If someone has a better on in mind, please suggest one
> change link

- docs/sphinx/conf.py
The job started failing today
I have restarted it but it looks like a problem on PE side
excluding for now
cc @dgault
> exclude perkinelmer

- pom.xml
Bumping the version to 1.2.9 to match the version bump in other repos.
> Bump logback version from 1.2.0 to 1.2.9

- docs/sphinx/conf.py
- docs/sphinx/ome-tiff/index.rst
Adding a new member of the ``supported`` list on https://docs.openmicroscopy.org/ome-model/latest/ome-tiff/index.html 
cc @dgault @jrswedlow
> Add Media Cybernetics

- docs/sphinx/conf.py
Adding bitplane link to the ignore list due to multiple failures in the daily link checks: https://merge-ci.openmicroscopy.org/jenkins/job/OME-MODEL-linkcheck/988/console
> Add bitplane to link check ignore list

- pom.xml
Bumping ome-common to the latest version
> Bump ome-common to 6.0.16

- ome-xml/src/main/java/ome/xml/meta/MetadataConverter.java
Error reporting in the new CI during the Bioformats-build
> fix error reported when building doc

- .github/workflows/maven.yml
- .github/workflows/publish_pypi.yml
- .github/workflows/tox.yml
- tox.ini
* Upgade checkout action
* Add support for Python 3.11
* Run on Ubuntu 22.04
> Gha update

- pom.xml
Bumping versions to match https://github.com/ome/bioformats/pull/3956
> Bump slf4j and logbook versions

- pom.xml
Bumping ome-common to latest version
> Bump ome-common version to 6.0.22

- docs/sphinx/ome-tiff/index.rst
cf. mailing list request of a user (confusinly, search in "security" mailing list to find the relevant request)
cc @jburel @dgault
> Add Telight to list of ome-tiff cf. mailing list

- xsd-fu/python/ome/modeltools/object.py
> Delete dead code

- ome-xml/src/test/resources/testng.xml
- pom.xml
See also https://github.com/ome/ome-common-java/pull/96
> Bump logback to version 1.3.15
