README.md
ome-xml/pom.xml
pom.xml
specification/pom.xml

In preparation of the upcoming release to Maven Central, this PR:
- fixes the top-level README
- bumps the release version to 5.3.0
/cc @rleigh-codelibre @dgault @melissalinkert

Bump release version to 5.3.0

---

README.md

See https://github.com/sbesson/ome-model/tree/badges for the review of this PR
Note that I have only linked to the `ome-xml` component but we could add badges for the other components.

Add badges for Maven Central and Javadocs

---

specification/publish

Following the filtering of the specification component, the creation of the intermediate indexes was in a broken state. This commit should restore the index creation.

Fix schema publication script post-migration of the repository

---

pom.xml

Needed for testing https://github.com/ome/ome-common-java/pull/8 and https://github.com/openmicroscopy/bioformats/pull/2648

Use ome-common 5.3.1

---

ome-xml/pom.xml

Noticed in https://github.com/openmicroscopy/bioformats/pull/2661#issuecomment-260919988, the `ome-xml` POM still contains unnecessary references to the OME artifactory.

Remove OME artifactory from OME-XML pom

---

pom.xml

Post components decoupling, this PR reviews the developers to use the following conventions discussed with @jburel and @joshmoore:
- lists the team as the main developers (matching the behavior of webapps) and uses the ome-devel email
- lists all contributors of the repository as contributors

Review developers section of the parent POM

---

ome-xml/src/main/cpp/ome/xml/model/OMEModelObject.h
ome-xml/src/main/cpp/ome/xml/model/OriginalMetadataAnnotation.cpp
ome-xml/src/main/cpp/ome/xml/model/OriginalMetadataAnnotation.h
ome-xml/src/main/cpp/ome/xml/model/detail/OMEModelObject.cpp
ome-xml/src/main/cpp/ome/xml/model/detail/OMEModelObject.h
specification/src/main/java/ome/specification/XMLMockObjects.java
specification/src/main/resources/transforms/2008-09-to-2009-09.xsl
xsd-fu/templates-cpp/OMEXMLModelObject.template
xsd-fu/templates-java/OMEXMLModelObject.template

- OMEXMLModelObject template:
- Remove the assumption that the element name will always match the class name;
this is incorrect for AffineTransform and Transform.
- Make the OMEModelObject::asXMLElement(Document, Element) method public
for both C++ and Java.
- The caller of asXMLElement sets the element name and passes in the element
- Don't use return value of asXMLElement (Java) and don't return a value at all (C++)
- Remove the sanity check that the element name and class name match, since
it is incorrect; for C++ deprecate the validElementName method and always
return true, for Java remove the inline check.
- Handle setting the class name differently for abstract (use derived class
name) and non-abstract (use property name).  This does mean derived classes
can't use the property name, …

Make ROI transforms functional

---

pom.xml

Following the comment from @mtbc in https://github.com/ome/ome-model/pull/15#discussion_r91043917, this PR reorganizes the ome-model POM to follow the Maven ordering convention.
See https://maven.apache.org/developers/conventions/code.html for more details

Re-order the POM following the code convention

---

CMakeLists.txt
docs/doxygen/CMakeLists.txt

This is to match the maven project name and give the sphinx manual
the correct name.
See https://github.com/ome/ome-cmake-superbuild/pull/109 for testing instructions.

build: Change cmake project name to ome-model

---

docs/sphinx/pom.xml

Testing: check artefact name, now `ome-model-doc-5.3.2-SNAPSHOT-manual.*`

build: Use -doc rather than -docs in artefact name

---

docs/sphinx/developers/id-and-lsid.rst
docs/sphinx/developers/ome-units.rst
docs/sphinx/ome-tiff/specification.rst
docs/sphinx/ome-tiff/tools.rst
docs/sphinx/ome-xml/index.rst

The model docs jobs have been failing the linkcheck step regularly in the last few days. This PR tries to mitigate the issue by:
- removing the link to the full specification documentation for LSID. The PDF is now restricted to members only and not public
- using HTTPS instead of HTTP in a few places

Fix intermittent hyperlinks

---

ome-xml/src/main/cpp/ome/xml/CMakeLists.txt
ome-xml/src/main/cpp/ome/xml/meta/Convert.cpp
ome-xml/src/main/cpp/ome/xml/meta/MetadataModel.h
ome-xml/src/main/cpp/ome/xml/meta/MetadataRoot.h
ome-xml/src/main/cpp/ome/xml/meta/OMEXMLMetadataModel.cpp
ome-xml/src/main/cpp/ome/xml/meta/OMEXMLMetadataModel.h
ome-xml/src/main/cpp/ome/xml/meta/OMEXMLMetadataRoot.cpp
ome-xml/src/main/cpp/ome/xml/model/OMEModel.h
ome-xml/src/main/cpp/ome/xml/model/OMEModelObject.h
ome-xml/src/main/cpp/ome/xml/model/detail/OMEModel.cpp
ome-xml/src/main/cpp/ome/xml/model/detail/OMEModel.h
ome-xml/src/main/java/ome/xml/meta/MetadataModel.java
ome-xml/src/main/java/ome/xml/meta/MetadataRoot.java
ome-xml/src/main/java/ome/xml/meta/OMEXMLMetadataModel.java
ome-xml/src/main/java/ome/xml/model/OMEModelImpl.java
ome-xml/src/test/cpp/model.cpp
specification/src/main/java/ome/specification/XMLMockObjects.java
xsd-fu/templates-cpp/AggregateMetadata.template
xsd-fu/templates-cpp/DummyMetadata.template
xsd-fu/templates-cpp/FilterMetadata.template
xsd-fu/templates-cpp/MetadataStore.template
xsd-fu/templates-cpp/OMEXMLMetadata.template
xsd-fu/templates-cpp/OMEXMLModelObject.template
xsd-fu/templates-java/AggregateMetadata.template
xsd-fu/templates-java/DummyMetadata.template
xsd-fu/templates-java/FilterMetadata.template
xsd-fu/templates-java/MetadataStore.template
xsd-fu/templates-java/OMEXMLMetadataImpl.template
xsd-fu/templates-java/OMEXMLModelObject.template
xsd-fu/xsd-fu

This is part 1 of the proposed refactoring in https://docs.google.com/document/d/1bzczgG2QyujCsCvR2kSAGl5hj-NJuIikgFAC3fDkqvs/edit# and https://trello.com/c/hnpxmvhe/52-extended-annotation-support-pt-i
- OME implements OMEModel
- OMEModelImpl (Java) and detail::OMEModel (C++) are no longer used and are deprecated; OME implements OMEModel directly, and OMEModelObject indirectly
- MetadataRoot replaced by MetadataModel
- OMEXMLMetadataRoot replaced by OMEXMLMetadataModel
Testing:
- Check generated source changes
- Check builds remain green
- Check bioformats build with and without https://github.com/openmicroscopy/bioformats/pull/2712
- Check ome-files-cpp build with and without https://github.com/rleigh-codelibre/ome-files-cpp/tree/ome-model-base (this is PR …

OME element implements OMEModel

---

docs/sphinx/developers/EnumTool.rst
docs/sphinx/index.rst
docs/sphinx/ome-tiff/index.rst
docs/sphinx/ome-tiff/specification.rst
docs/sphinx/ome-tiff/tools.rst
docs/sphinx/ome-xml/index.rst

This updates all the links which are being permanently redirected* by the merge build (https://ci.openmicroscopy.org/view/Docs/job/MODEL-merge-docs/) - builds should be green with only our own links redirected to current versions*) and the staging pages should be unchanged.
N.B. I've replaced the TIFF link altogether because the Adobe link was redirecting somewhere irrelevant and is another site which wants you to identify your country of origin before it'll point you at links - hopefully the wiki is sufficient.
*with the exception of the GELifeSciences link which wants you to pick a country so doesn't play nicely with the linkchecker

Fix permanent redirects

---

ome-xml/src/main/cpp/ome/xml/model/OriginalMetadataAnnotation.h
ome-xml/src/main/cpp/ome/xml/model/detail/OMEModelObject.cpp
xsd-fu/templates-cpp/OMEXMLModelObject.template
xsd-fu/templates-cpp/OMEXMLModelObject_XMLAnnotation_asXMLElement_Value.template
xsd-fu/templates-cpp/OMEXMLModelObject_XMLAnnotation_update_Value.template

See [trello card](https://trello.com/c/WR9yB2L9/84-metadata-performance) for more details.
`getTagName()` already returns a tag without a namespace, making this pointless.  Removing the unnecessary stripping is a minor performance enhancement.
The major change here is to remove all use of xerces DOMNodeList (ome::common::xml::dom::NodeList).  This has very inefficient iterator performance--O(n) for every indexed access.  Swapping this with the lower level Node `getFirstChild()` and `getNextSibling()` results in a dramatic speedup (around 2 mins to 4 seconds for the mitocheck data!)
Testing: Check builds remain green.
Check the performance of the ome-files-performance tests; they should be significantly faster, for mitocheck in particular.
Test data: download …

ome-xml: Performance improvements

---

xsd-fu/templates-cpp/OMEXMLModelObject.template

See https://trello.com/c/BlQrTZf9/1-metadata-bug.  Coupled with https://github.com/ome/ome-files-cpp/pull/57 this allows round-tripping of ROIRefs.
Testing: Run `ome-files info --omexml` on the mitocheck sample.  You'll see ImageRef and ROIRef elements; ROIRef were previously absent.  Anything else missing?

xsd-fu: C++ OMEXMLModelObject template inserts missing links

---

docs/sphinx/ome-tiff/data.rst
docs/sphinx/ome-tiff/file-structure.rst
docs/sphinx/ome-tiff/specification.rst

In preparation of the addition of the new OME-TIFF filesets, this PR reviews the content of the existing page with the following modifications:
- the sections are reorganized to differentiate artificial from biological (real-world?) datasets
- the Bio-Formats generated table is updated to list all the extensions
- all tables are updated to use a unified `Image Dimensions (XYZCT)` column
- the final paragraph about multi-file OME-TIFF filesets is collapsed into a single descriptive table
A few questions to be answered as part of the review:
- does the new layout make sense/simplify the addition of new datasets
- is the content of the new tables informative
- should the `Modulo` section be reorganized as a table (most of the information is quite row-specific)
- any better suggestions than …

OME-TIFF samples: reorganization

---

docs/sphinx/ome-tiff/data.rst

This PR aims at registering the converted BBBC & MitoCheck datasets used for the [benchmark work](https://github.com/openmicroscopy/ome-files-performance) into the official OME-TIFF documentation as public OME-TIFF samples representative of HCS and ROI data.
A few questions while working on the initial draft:
- is there other representative data we should add to the tables (columns/rows/fields, ROIs)
- with regard to the data layout, we currently have a single plate converted. There was a brief discussion of converting other plates to test some scaling with @rleigh-codelibre. Is there a case for anticipating and starting to organize into subfolders e.g. `BBBC/BBBC0017/NIRHTa-0001.ome.tiff` or should we consider this when the use case shows up?
/cc @hflynn @AnneCarpenter

Add BBBC & MitoCheck datasets to the OME-TIFF samples page

---

docs/sphinx/ome-tiff/code.rst
docs/sphinx/ome-tiff/specification.rst

See https://ci.openmicroscopy.org/view/Failing/job/MODEL-merge-docs/84/console
This updates the BigTIFF links to match the one used in Bio-Formats docs and should make the build green again.
Staged at http://www.openmicroscopy.org/site/support/ome-model-staging/ome-tiff/specification.html and http://www.openmicroscopy.org/site/support/ome-model-staging/ome-tiff/code.html

Fix bigTIFF link to match BF

---

docs/doxygen/ome-xml.dox.cmake
ome-xml/src/main/cpp/ome/xml/meta/BaseMetadata.h
ome-xml/src/main/cpp/ome/xml/meta/Metadata.h
ome-xml/src/main/cpp/ome/xml/meta/MetadataRoot.h
ome-xml/src/main/cpp/ome/xml/meta/OMEXMLMetadataRoot.h
ome-xml/src/main/cpp/ome/xml/model/OMEModel.h
ome-xml/src/main/cpp/ome/xml/model/OMEModelObject.h
ome-xml/src/main/cpp/ome/xml/model/detail/OMEModelObject.h
ome-xml/src/main/cpp/ome/xml/model/enums/EnumerationException.h
xsd-fu/templates-cpp/MetadataRetrieve.template
xsd-fu/templates-cpp/MetadataStore.template
xsd-fu/templates-cpp/OMEXMLModelEnum.template
xsd-fu/templates-cpp/OMEXMLModelObject.template
xsd-fu/templates-cpp/OMEXMLModelQuantity.template

Upgrade to the latest Doxygen configuration file version.
Doxygen can't handle deleted methods too well--it complains about
them not being documented despite them not existing at all, so
skip them entirely.
Testing: Check all builds remain green.

Update API reference including use of deleted methods

---

xsd-fu/templates-cpp/OMEXMLModelObject.template

[Trello](https://trello.com/c/S7fIcUi9/7-correct-xsd-fu-template-mistake)
Compare with the Java template, line 433.  We make it use each element for the NodeList we are iterating over, rather than the current element.
Testing: Looking at the generated sources, this codepath appears to be unused at present.  Maybe simply confirming we match the Java behaviour is sufficient to check?

xsd-fu: Correct C++ model object template using wrong element

---

docs/sphinx/conf.py
docs/sphinx/developers/index.rst
docs/sphinx/developers/sample-files.rst
docs/sphinx/developers/using-ome-xml.rst
docs/sphinx/index.rst
docs/sphinx/ome-tiff/code.rst
docs/sphinx/ome-tiff/specification.rst
docs/sphinx/ome-xml/index.rst
docs/sphinx/ome-xml/java-library.rst
docs/sphinx/schemas/index.rst

Removes old plone URLs (except the citation page cf. https://trello.com/c/DR1L8nDA/100-add-citations) and updates copyright years

Update URLs & copyright years

---

README.md
docs/sphinx/index.rst

Discussed with Seb earlier that the new versioning of the Model docs is a bit confusing because the only versioning discussed within the docs is the Schema versioning which is different, so I've added a note to try and clarify if anyone else is confused.
While I was here I noticed I'd missed the docs links in the README when I updated them in the docs. Note that I can't update the C++ API docs as they haven't been migrated, as noted on https://trello.com/c/aKaDecyV/78-link-to-c-api-docs

Add versioning note & update README

---

ome-xml/src/main/cpp/ome/xml/OMEXMLConfig.cmake.in

This is added implicitly by find_dependency.
See https://github.com/ome/ome-common-cpp/pull/51 for context.

cmake: Remove REQUIRED from exported configuration

---

docs/sphinx/index.rst
docs/sphinx/omero-pyramid/index.rst

See https://trello.com/c/XGsjTdcc/5-omero-pyramid-specification
```docs/sphinx/omero-pyramid/index.rst``` should be effectively the same as https://github.com/openmicroscopy/bioformats/blob/develop/docs/sphinx/developers/wsi.rst#internal-omero-pyramid-format-v100 - the only difference is the ```bf_doc``` links.

Move OMERO pyramid specification to model documentation

---

README.md
docs/sphinx/conf.py
docs/sphinx/index.rst
docs/sphinx/ome-tiff/code.rst
docs/sphinx/ome-tiff/data.rst
docs/sphinx/ome-tiff/index.rst
docs/sphinx/ome-tiff/specification.rst
docs/sphinx/ome-xml/index.rst
docs/sphinx/ome-xml/java-library.rst
docs/sphinx/pom.xml

The old http://www.svisionllc.com/ link isn't resolving to anything but https://www.drvtechnologies.com looks to be the right company (google has cached results to link them together as well as the name being right).
Also fixed the remaining plone link that is now migrated to the new website and updated the downloads links for BF & OME Files to just use the new pages on the website as they only need to link to the latest version anyway, and readme links to use https for downloads, website and docs.

Fix & update links

---

docs/sphinx/conf.py

Re: https://github.com/openmicroscopy/sphinx-ignore-links/issues/1
This removes use of the separate repo for listing links to be ignored (in future any links needing listed can be added to this file instead), also cleaned up omero role stuff which had been migrated to this repo and isn't used.

Remove sphinx-ignore-links & cleanup conf.py

---

docs/sphinx/ome-tiff/index.rst

This link was breaking the build this morning - see https://ci.openmicroscopy.org/view/Failing/job/MODEL-merge-docs/312/console and their website has a banner saying they are upgrading it so I've gone for just linking to the main page for now - there's no nice Deltavision landing page at the moment and I don't want to use a URL that then gets broken again as they upgrade.

Fix GE Healthcare Life Sciences link

---

CONTRIBUTING.md
README.md

See https://trello.com/c/oxWdJSKf/610-clean-up-remaining-links-to-site-support-old-docs-urls
This is redirected anyway but nice to have the cleanup done anyway.

Update doc links to use new doc URLs

---

docs/sphinx/ome-xml/index.rst

See https://trello.com/c/jUZXWOYY/3-ome-model-docs-ome-database
This page still contained a lot of legacy information from back when this was a wiki page, including information about the OME data model which is documented elsewhere in the manual.  The changes here restrict the page to describing the OME-XML file format only, removing information about the OME database and OME-XML data model dating back over a decade which is no longer relevant here.

docs: ome-xml: Remove references to OME-XML as a data model

---

docs/sphinx/conf.py

@sbesson notes on #63 that this URL seems to be working again now so this PR removes it from the ignore list.

Remove leica-microsystems.com from ignore list

---

.appveyor.yml
.travis.yml
docs/sphinx/pom.xml
ome-xml/pom.xml
pom.xml
specification/pom.xml

Same as https://github.com/ome/ome-common-java/pull/16 (see this PR for rationale and testing instructions).  Note ome-common and other dependencies are unchanged because it doesn't have a compile- or runtime-dependency upon the new version.

build: Update maven plugin versions

---

ome-xml/pom.xml
pom.xml

This is to allow `-Dome-common.version=...` or rewriting the configuration to work the same for all components.  This one was different for some reason.
Testing: check builds are green.

build: Unify component version property names

---

ome-xml/pom.xml
pom.xml
specification/pom.xml

Close: #71 
Same idea as https://github.com/ome/ome-stubs/pull/4
Note: Also check that you have `JAVA_HOME` set since for some reason this is a requirement for javadoc generation.
Testing: Check builds are green, and check you can release.
/cc @joshmoore

build: Use plugins from root pom

---

docs/sphinx/ome-tiff/index.rst

This link upset the build this morning and when I checked it, although it was working, it was pointing at content in German so thought I might as well update it.

Update dodgy link in OME-TIFF docs

---

xsd-fu/templates-cpp/OMEXMLModelObject.template
xsd-fu/templates-java/OMEXMLModelObject.template

Move `[SubResolution]FormatReader.getRotationTransform` to the `AffineTransform` class itself.  Use a static method for Java, and a regular constructor for C++ (where it can be specialised on a radian unit).
Testing: Check builds remain green for both Java and C++.
This will permit dropping of this implementation from `FormatReader` once released, and complete removal from `SubResolutionFormatReader`.

AffineTransform: Add createRotationTransform static method

---

xsd-fu/xsd-fu

This significantly reduces compile times (up to 30 minutes!).  Check out the build time trend graphs in jenkins for the various matrix combinations.  The source files for the model and enums are concatenated into single source files so >100 compiler invocations are reduced to two.  No C++ code changes, or any changes to the generated Java code.  Headers are still individual, so from the user's point of view there is zero change.
This can go into the next patch release or minor release (there are no code changes, so either is fine).
Testing: Check builds are green.

xsd-fu: Aggregate generated C++ source files into single source files for model and enums

---

docs/sphinx/conf.py

An improperly configured SSL certificate caused this link to fail.

Exclude definiens.com from the linkcheck

---

ome-xml/src/main/java/ome/xml/meta/MetadataConverter.java
ome-xml/src/main/java/ome/xml/model/AbstractOMEModelObject.java
specification/src/main/java/ome/specification/XMLMockObjects.java
xsd-fu/templates-java/MetadataStore.template

Four javadoc fixes.  Two are broken internal links.  Two are invalid markup (`<` and `>` in an email address interpreted as invalid XML, and a `</>` in an opening tag).
Testing: Check builds are green.

ome-xml: Javadoc fixes

---

.travis.yml
xsd-fu/templates-java/OMEXMLModelObject.template

Replace DatatypeConverter usage in order to fix JDK 11 build.
* cF
- https://docs.oracle.com/javase/8/docs/api/java/util/Base64.Encoder.html
- https://github.com/http-kit/http-kit/issues/356#issuecomment-369982659
* Tested with Dockerfile:
```
FROM maven:3-jdk-11
MAINTAINER ome-devel@lists.openmicroscopy.org.uk
RUN useradd -m ome
COPY --chown=ome:ome . /opt/ome-model/
USER ome
WORKDIR /opt/ome-model
RUN mvn clean install
```
(needs sphinx added)

Remove DatatypeConverter usage for JDK 11+

---

.gitignore
ome_model/experimental.py
setup.py

Combining work on/for:
* https://github.com/IDR/idr0047-neuert-yeastmRNA/pull/1
* https://github.com/spacetx/starfish/issues/603
this adds a simple Python interface (ome_model.experimental)
that will be deployed to PyPI for building OME-XML companion
files. Longer-term: these classes and methods should be code-
generated.

Add experimental OME-XML generation

---

.travis.yml

See https://github.com/ome/ome-common-java/pull/37 and https://github.com/openmicroscopy/bioformats/pull/3286#discussion_r240145628
Same testing procedure: Travis green is the only thing to check here

Extend Travis configuration to test OpenJDK8 and OpenJDK 11

---

ome_model/experimental.py

Follow up of #92, this expands the logic of the experimental Python module to generate companion OME-XML files using from any set of TIFF files including multi-page TIFFs.
To do so, two new objects are defined to handle [TiffData](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#TiffData) and [UUID](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#TiffData_UUID) elements allowing notably to pass the `TiffData` attributes.
An example of consumption of this API will be opened in the context of the `idr0053` study. Proposing this as `6.0.0a3`.

ome_model: add support for generating companion with multi-page TIFFs

---

ome-xml/src/main/java/ome/xml/meta/MetadataConverter.java

Backported from unmerged private PR.  Adds two public ```convertChannelMetadata``` methods to allow just one ```Channel``` and all of its linkages to be copied from a ```MetadataStore``` to a ```MetadataRetrieve```.  The behavior of ```convertMetadata(MetadataRetrieve, MetadataStore)``` should be unchanged.
This will allow ```loci.formats.ChannelSeparator``` to copy all channel metadata when performing channel separation, instead of just channel names.  See https://github.com/openmicroscopy/bioformats/blob/develop/components/formats-bsd/src/loci/formats/ChannelSeparator.java#L325

MetadataConverter: refactor Channel copying into separate public methods

---

docs/sphinx/ome-tiff/specification.rst

See https://trello.com/c/gMg5Miz9/23-ome-tiff-pyramid-specification
As we are converging towards a release of Bio-Formats 6, this PR proposes the set of changes to the OME-TIFF specification page to formalize the file format extension allowing to support pyramidal levels as proposed in https://openmicroscopy.github.io/design/OME005/. 
Summary of changes:
- reference to RFC 2119 and the Adobe TIFF specification
- definition of pyramidal terms and the scope of the pyramidal support in OME-TIFF
- definition of the storage of pyramidal levels using subIFDs

Pyramidal OME-TIFF specification addition

---

docs/sphinx/conf.py
docs/sphinx/ome-tiff/data.rst
docs/sphinx/ome-tiff/specification.rst

This lists the official OME-TIFF examples that were generated using Bio-FOrmats
6.0.0-rc1 and will be released as part of the version 6.0.0 of the OME Model
component.
An anchor is also added to the sub-resolution section for referencing purposes.

Update OME-TIFF sample page with sub-resolutions OME-TIFF examples

---

docs/sphinx/conf.py
docs/sphinx/schemas/june-2016.rst

Ignore GitHub OME links for checking and update for a relocated repository.

Don't check GitHub OME link.

---

ome_model/experimental.py

Discovered while creating a minimal example of usage of this experimental library in https://forum.image.sc/t/spw-and-patterns/38625/5
If `z,c,t` are not passed or parsed  from the TIFF files, the default value in the`add_tiff()` is currently `NOne` and gets serialized as `"None"` in the resulting OME-XML which is obviously invalid.
Using a variation of the sample snippet copied in the image.sc issue, the following example can be used to test this PR
```
#!/usr/bin/env python
from ome_model.experimental import Plate, Image, create_companion
rows = 1
columns = 4
plate = Plate("test", rows, columns)
for row in range(rows):
for column in range(columns):
well = plate.add_well(row, column)
basename = "%s%s" % (chr(row + 65), column)
image = Image(basename, 512, 512, 1, 1, 1) …
```

Fix default z,c,t values of add_tiffdata

---

docs/sphinx/conf.py
docs/sphinx/ome-tiff/index.rst
docs/sphinx/specifications/index.rst

- Ignores external links blocked or timing out
- update JCB links 
Background: the NCBI PMC HEAD requests have some user-based agent filtering into place and reject the default agent set by Sphinx:
```
>>> requests.head('https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6774793/')
<Response [403]>
>>> requests.head('https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6774793/', headers={'User-Agent': 'Mozilla/5.0'})
<Response [200]>
>>> requests.head('https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6774793/', headers={'User-Agent': 'Sphinx/3.1.2 requests/2.23.0 python/3.7.6'})
<Response [403]>
>>> requests.head('https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6774793/', headers={'User-Agent': 'Mozilla/4.0'})
<Response [200]>
```

Linkcheck fixes

---

docs/sphinx/ome-tiff/data.rst

See https://merge-ci.openmicroscopy.org/jenkins/job/OME-MODEL-linkcheck/19/console
The latest release of Sphinx now fails the linkcheck for individual well URLs due a redirect excess. This can be reproduced using
```
$ curl -IL https://idr.openmicroscopy.org/webclient/?show=well-771034
...
curl: (47) Maximum (50) redirects followed
```
This PR  fixes the issue by using the canonical gallery study URL for the dataset provenance rather than the individual well.
There might be a large issue with the recursive IDR nginx redirects and I am unclear how this resolves in the web browser. @manics worth turning into an IDR/deployment issue or do you have a feeling for the source of the problem?

Fix hyperlink to idr0013 URL

---

.travis.yml
setup.py

In preparation of the 6.1.2 release, this PR is meant to reduce the management of the Python component of this repository:
- the `ome-model` version is now read directly from `pom.xml` and converted into a PEP440 compliant suffix for SNAPSHOTS
- a Travis CI provider is now declared which should upload to PyPI on tags. 
With these changes, I'd expect to simplify the release process and have the steps describe in https://docs.openmicroscopy.org/contributing/java-development.html#release-process also covering the release of the Python component. There is still a manual post Sonatype deployment step to unzip the documentation artifact under https://docs.openmicroscopy.org/ome-model/.

Add PyPI deployment to Travis

---

.travis.yml
MANIFEST.in
ome_model/experimental.py
test/unit/test_image.py
tox.ini

This PR inclues a set of improvements for the `Image/Pixels/Channel` created by the `ome_model` library driven by in-progress IDR work on HCS RGB companion files /cc @dominikl 
- the [Channel.Name](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Channel_Name) and [Channel.Color](https://www.openmicroscopy.org/Schemas/Documentation/Generated/OME-2016-06/ome_xsd.html#Channel_Color) attributes are optional as per the OME schema. In the case of many RGB images typically these values are irrelevant. 7837240  changes the `Channel` constructor and `Image.add_channel` method to turn these metadata fields into optional key/value pairs rather than mandatory arguments and handling missing arguments/`None`
-  1ae8b58  refines the current `Image.validate()` …

ome_model: channel fixes

---

ome_model/experimental.py

`sys.stdout` in Jupyter notebooks may not have a `buffer` attribute.
To test: run `create_companion(images=[companion])` (i.e. use the default `out` parameter) in a Jupyter Notebook.
See e.g. https://github.com/Yelp/mrjob/pull/1443

Ensure stdout works in Jupyter Notebooks

---

ome_model/experimental.py
test/unit/test_image.py

This API addition had  driven in the context of `idr0065` - see https://github.com/IDR/idr0065-camsund-crispri/blob/master/scripts/generate_companions.py#L146 to populate the `Plane` metadata using the submitted timestamp/exposure information - see https://idr.openmicroscopy.org/webclient/img_detail/9022301 for instance. As I was trying to re-use the API for `idr0092`, I realized I never backported the change.
In terms of style, the new `Plane` object explicitly defines the `z/c/t` arguments as well as an `options` dictionary which takes all the optional `Plane` attributes.   A minimal example of consumption of this API is illustrated below:
```
from ome_model.experimental import Image, create_companion
i = Image("test", 256, 512, 1, 2, 2)
i.add_plane(c=0, z=0, t=0, options={'DeltaT': …
```

ome-model: add support for Plane population

---

.gitignore
ome_model/experimental.py
setup.py
test/unit/test_image.py

Discussed with @manics and @joshmoore, this PR adds some logic to `setup.py` to write the current module version under `ome_model/version.py` using the `__version___` attribute - see https://www.python.org/dev/peps/pep-0396/. If `__init__.py` or another variable name is preferable, I have no strong opinion but I was not able to find a PEP authoritatively defining the recommended behavior.
The module is also updated to store `ome_model x.y.z[.dev0]` in the `OME.Creator` attribute similarly to the implementation in Bio-Formats - see https://github.com/ome/bioformats/pull/2207.

ome-model: allow to introspect version

---

.travis.yml

The switch to build stages in #120 has broken the logic of the deployment stage so that `ome-model 6.2.0` was not automatically pushed to PyPI. This PR fixes the issue by moving the deployment to a dedicated build stage only executed on tags - see https://docs.travis-ci.com/user/build-stages/#build-stages-and-deployments
This re-uses most of the logic already implemented in https://github.com/ome/ome-zarr-py/blob/master/.travis.yml. https://travis-ci.org/github/sbesson/ome-model/jobs/727818756 also tests the conditional deployment logic (which failed due to the absence of credentials as expected)
Proposed tag `6.2.1`

Convert Travis CI deployment into a build stage

---

ome-xml/src/main/java/ome/xml/model/OMEModelImpl.java

This is a small fix I was going to make for OME Files (see [MR !116](https://gitlab.com/codelibre/ome/ome-model/-/merge_requests/116/diffs?w=1)).  It prevents the addition of null references to the model which would cause problems later on when traversing the model data after the initial import.  Should not be seen in normal use, but it protects against unintentional incorrect use.  Returns a failure status as for other failure scenarios, so the caller will be notified the addition failed should they care to check.

OMEModelImpl: Do not permit the addition of null references

---

docs/sphinx/conf.py

The linkcheck has been failed since April 6th 2021 due to an expired SSL certificate.
The website owners have been contacted separately.

Temporarily exclude fei.com

---

ome-xml/src/main/java/ome/xml/meta/MetadataConverter.java

Correctly initialise wellAnnotationRefCount.
This defect was found during static analysis of the source tree.  I will have several additional fixes to come, plus a number of performance and cosmetic improvements also picked up by the static analyser.
Testing: Try converting an OME-TIFF with `WellAnnotationRef`s.  You should see that they are stripped out during conversion.  Repeat with this PR.  You should find they are now correctly preserved.
Closes: #130

MetadataConverter: Fix dropping of WellAnnotationRefs during conversion

---

ome_model/experimental.py
test/unit/test_plate.py

Triggered by an IDR submission, the following code exposes the issue
```python
from ome_model.experimental import Plate, Image, create_companion
for i in range(5):
plate = Plate(str(i), 1, 1)
well = plate.add_well(0,0)
image = Image(
str(i), 10, 10, 1, 2, 1,
order="XYZCT", type="uint16")
image.add_tiff(str(i) + '.tif')
well.add_wellsample(0, image)
create_companion(plates=[plate], out=str(i) + '.companion.ome')
```
While expecting this will create 4 companion OME files with 1 plate/1 well/1 well sample/1 image each, the second companion contains 2 images, the third 3...
Tracing down the source of the issue comes down to the usage of empty lists as default arguments which is a classical Python gotcha as these are mutable. At the moment, a workaround would be to explicitly pass a new empty …

ome_model: do not use mutable default arguments

---

specification/src/main/resources/transforms/2008-09-to-2009-09.xsl

This is a follow up to #142 and should see the unit tests in ome/bioformats#3695 turn green.
The issue appears to have been due to CustomAttributes being able to be located in 4 different locations:
top level under OME
under images
under images/feature
under dataset
The non top level CustomAttributes were being transformed into XMLAnnotations but embedded in the original element, be it Image or Dataset, this is an invalid location for it and thus it was not being recognised when converted back to an OME-Model object. This PR aims to move all CustomAnnotations to the top OME level before transforming them. If you have multiple CustomAttributes at different levels then you will get multiple XMLAnnotations inside a single StructuredAnnotations.
Fixes #142

2008-09 to 2009-09: Move CustomAttributes transforms to top level

---

docs/sphinx/conf.py
docs/sphinx/ome-xml/java-library.rst

Also only refer to Maven Central as the hosting platform for the artifacts
Fixes https://github.com/ome/ome-model/issues/152

Update java-library page to point to javadoc.io

---

docs/sphinx/ome-tiff/specification.rst

Link to the TIFF standard has been broken on the adobe site for a number of days (https://latest-ci.openmicroscopy.org/jenkins/job/OME-MODEL-linkcheck/528/console). 
See posts [Adobe & TIFF spec](https://community.adobe.com/t5/using-the-community-discussions/broken-link-to-open-standards-on-adobe-io/m-p/12753322) and ​​[second post](https://experienceleaguecommunities.adobe.com/t5/adobe-i-o-cloud-extensibility/broken-link-to-open-standards-on-adobe-io/td-p/441124).

Update link to TIFF standard

---

docs/sphinx/ome-tiff/index.rst

The old link had been redirecting to the new location. Changing to point to the redirected location and update the company name, see below:
Previously named Accelrys, it is a wholly owned subsidiary of [Dassault Systèmes](https://en.wikipedia.org/wiki/Dassault_Syst%C3%A8mes) after an April 2014 acquisition[[1]](https://en.wikipedia.org/wiki/BIOVIA#cite_note-1) and has been renamed BIOVIA

Accelrys renaming and link update

---

docs/sphinx/ome-tiff/specification.rst

The current link (https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFFPM6.pdf) is currently unavailable. For BF 6.9.0 we updated the TIFF spec to point to https://www.loc.gov/preservation/digital/formats/fdd/fdd000022.shtml, the link on that page to an archived version of the Adobe PageMaker 6.0 pdf is what I have used here.

Update link to Adobe PageMaker 6.0 tech note

---

docs/sphinx/ome-tiff/data.rst

This PR updates the sample data page of the OME-TIFF specification to point at the new representative samples of the BBBC017 plate which were recently generated and published under https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/BBBC017/.
These samples are being tested by the daily CI builds and have been used for the functional testing of https://github.com/ome/bioformats/pull/3831#pullrequestreview-1100874964
A note is also added to explain why the former OME-TIFF should be considered as deprecated and its usage replaced.

BBBC017: new representative OME-TIFF samples

---

.github/workflows/tox.yml

Check that the build is green
Background https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Switch to new output command

---

xsd-fu/python/ome/modeltools/property.py
xsd-fu/templates/java/AggregateMetadata.template
xsd-fu/templates/java/FilterMetadata.template
xsd-fu/templates/java/MetadataRetrieve.template
xsd-fu/templates/java/OMEXMLMetadataImpl.template
xsd-fu/templates/java/OMEXMLModelEnum.template
xsd-fu/templates/java/OMEXMLModelEnumHandler.template
xsd-fu/templates/java/OMEXMLModelObject.template
xsd-fu/templates/java/OMEXMLModelObject_XMLAnnotation_asXMLElement_Value.template

Following static analysis of the ome-model source tree, the following remediation of the xsd-fu Java templates has been performed:
OME Model Object template:
* Removal of unnecessary casts
* Removal of unused variables
* Special-casing of `String` and numeric type member usage to remove unnecessary use of `toString` and `valueOf`
* Removal of special-cases which are never used
* Suppression of warnings for methods which are unused [within this source tree; many are used externally]
OME Model Enums and Handlers templates:
* Correction of double-assignment of units
* Suppression of unused method warnings [within this source tree; many are used externally]
OME Model Object and Enums templates:
* Use `<>` for generics where the type can be inferred
* Removal of unused imports
MetadataStore …

Static analysis code remediation: xsd-fu Java templates

---

ome-xml/src/main/java/ome/specification/XMLMockObjects.java
ome-xml/src/main/java/ome/specification/XMLWriter.java
ome-xml/src/main/java/ome/units/UNITS.java
ome-xml/src/main/java/ome/units/quantity/Angle.java
ome-xml/src/main/java/ome/units/quantity/ElectricPotential.java
ome-xml/src/main/java/ome/units/quantity/Frequency.java
ome-xml/src/main/java/ome/units/quantity/Length.java
ome-xml/src/main/java/ome/units/quantity/Power.java
ome-xml/src/main/java/ome/units/quantity/Pressure.java
ome-xml/src/main/java/ome/units/quantity/Temperature.java
ome-xml/src/main/java/ome/units/quantity/Time.java
ome-xml/src/main/java/ome/units/unit/Unit.java
ome-xml/src/main/java/ome/xml/meta/MetadataConverter.java
ome-xml/src/main/java/ome/xml/model/AbstractOMEModelObject.java
ome-xml/src/main/java/ome/xml/model/MapPair.java
ome-xml/src/main/java/ome/xml/model/OMEModel.java
ome-xml/src/main/java/ome/xml/model/OMEModelImpl.java
ome-xml/src/main/java/ome/xml/model/ReferenceList.java
ome-xml/src/main/java/ome/xml/model/primitives/NonNegativeFloat.java
ome-xml/src/main/java/ome/xml/model/primitives/NonNegativeInteger.java
ome-xml/src/main/java/ome/xml/model/primitives/NonNegativeLong.java
ome-xml/src/main/java/ome/xml/model/primitives/PercentFraction.java
ome-xml/src/main/java/ome/xml/model/primitives/PositiveFloat.java
ome-xml/src/main/java/ome/xml/model/primitives/PositiveInteger.java
ome-xml/src/main/java/ome/xml/model/primitives/PositiveLong.java
ome-xml/src/main/java/ome/xml/model/primitives/PrimitiveNumber.java
specification/src/main/java/ome/specification/OmeValidator.java
specification/src/main/java/ome/specification/SchemaResolver.java

Following static analysis of the ome-model source tree, the following remediation of the ome-xml and specification Java components has been performed:
Both ome-xml and specification:
* Addition of missing `final` qualifiers
* Removal of inferrable types when using generics (replaced with `<>`)
* Remove unnecessary boxing and unboxing
ome-xml:
* Simplify complex conditional
* Make ignored exceptions explicit
* Replace complex sets of conditionals with switch
* Use `Map.computeIfAbsent()` to simplify list creation
* Remove `public` modifier from interface (it's public by default)
* Replace use of `StringBuilder` for performance
* Return values directly rather than using an unneeded temporary
* Add suppression for unused return values [within the ome-model source tree]
* Add suppression for …

Static analysis code remediation: ome-xml and specification Java sources

---

ome-xml/src/main/java/ome/specification/XMLMockObjects.java

See https://github.com/ome/bioformats/issues/3810

XMLMockObjects: make artificial SHA1 schema-compliant

---

xsd-fu/templates/java/OMEXMLModelEnumHandler.template

Closes: #132 
Testing: You will need to check which type each primitive type extends and confirm that the ordering is from most-derived to least-derived so that all types are correctly processed.  You could alternatively run a static analyser on the generated sources to confirm that none of the conditional blocks are unreachable (which is how the defect was originally found).
Generated source changes: Download the diff from [here](https://gitlab.com/rleigh/ome-model/-/jobs/875951611) or generate the diff yourself.

OMEXMLModelEnumHandler template: Correct type evaluation order

---

xsd-fu/templates/java/OMEXMLModelEnum.template

Static analysis highlighted a bad use of `return` within a `finally` block.  This was indeed unnecessary and replaceable with an ignored `catch` block.
Testing: Nothing specific required; the effective code flow is unchanged with or without exceptions, but we no longer return from within a `finally` block.
Generated source changes: Download the diff from [here](https://gitlab.com/rleigh/ome-model/-/jobs/875962162) or generate the diff yourself.

OMEXMLModelEnum template: Correct exception handling

---

ome-xml/src/main/java/ome/xml/model/AbstractOMEModelObject.java
xsd-fu/templates/java/OMEXMLModelObject.template

This PR is a second version of #81 but is Java-only and omits the C++ changes which are no longer applicable.  Please also see the discussion on that PR.
This PR corrects some long-standing issues in the Java reference processing implementation.
- `OMEModelObject::link` implementations always chained up to their parent before handling the linking themselves.  This works, but would result in the parent issuing a warning if it couldn't handle it, despite the child later handling the link.  We now chain up only if the child can't handle the link, and issue a warning right at the top if nothing handled it.  This solves a number of annoying Java model serialisation warnings which are completely bogus.
In effect, you will see that setting an `AnnotationRef` on `Detector` or any other element …

ome-xml: java: Don't report unhandled links prematurely

---

.github/workflows/maven.yml
.github/workflows/publish_pypi.yml
.github/workflows/tox.yml

- bump versions of core GitHub actions as per the deprecation warning -  https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
- test the code generation on Python 3.8, 3.9, 3.10 - see https://endoflife.date/python

GH CI maintenance upgrades

---

.github/workflows/maven.yml
xsd-fu/python/generateDS/generateDS.py

Might need to exclude some Java 21 + Python combinations from the matrix.

Add JDK 21 to build matrix

---

ome-xml/pom.xml
pom.xml

See also https://github.com/ome/ome-common-java/pull/88
For JDK8, bump org.testng:testng to the last supported release for this version i.e. 7.5
For JDK11+, bump org.testng:testng to the latest release 7.9.0

Use Maven profiles to handle different versions of TestNG

---

xsd-fu/templates/java/OMEXMLModelObject.template

Suggested in https://github.com/glencoesoftware/ome-omero-roitool/pull/37#pullrequestreview-1850691851

Add model object API to clear each list of associated objects

---

ome_model/experimental.py
setup.py

See #194
This is the first step of the removal of the `ome_model` Python code from this repository. `DeprecationWarning` are added to the module and the project name and description should be amended on PyPI on the next release. Both should redirect towards other libraries like `ome-types`.
Once merged and released, we can open a follow-up PR to cleanup the code entirely.

Deprecate ome_model package

---

specification/src/main/resources/transforms/util/write-transforms.py
xsd-fu/python/generateDS/generateDS.py
xsd-fu/python/generateDS/process_includes.py
xsd-fu/python/ome/modeltools/entity.py
xsd-fu/python/ome/modeltools/exceptions.py
xsd-fu/python/ome/modeltools/language.py
xsd-fu/python/ome/modeltools/model.py
xsd-fu/python/ome/modeltools/object.py
xsd-fu/python/ome/modeltools/property.py
xsd-fu/python/ome/modeltools/template.py
xsd-fu/python/util.py
xsd-fu/xsd-fu

I'm assuming all scripts are Python 3 scripts, except this one:
[specification/src/main/resources/transforms/util/write-transforms.py](https://github.com/ome/ome-model/blob/master/specification/src/main/resources/transforms/util/write-transforms.py)
The latter has been marked as a Python 2 script.

Apply ruff rules to Python scripts

---

requirements.txt

While `Genshi` does seem to require `six`, we should let it handle its own dependencies. That's what `pip` and other package installers are for.

`six` is not a direct dependency anymore

---

xsd-fu/python/generateDS/generateDS.html
xsd-fu/python/generateDS/process_includes.py

We use only the ASCII character set, so switching is straightforward.

Switch to utf-8 encoding for Python scripts

---

specification/src/main/resources/transforms/util/write-transforms.py

I have checked that the script regenerates an identical `specification/src/main/resources/transforms/ome-transforms.xml` file.
Fixes #207.

Port script to Python 3

---

xsd-fu/python/generateDS/generateDS.py
xsd-fu/python/generateDS/process_includes.py
xsd-fu/python/ome/modeltools/model.py
xsd-fu/python/ome/modeltools/property.py

Are all scripts supposed to have switched to Python 3 (except for those in #207)?

Apply ruff preview rules to Python scripts

---

xsd-fu/python/generateDS/generateDS.html
xsd-fu/python/generateDS/generateDS.py
xsd-fu/python/generateDS/process_includes.py

Fixes https://github.com/ome/ome-model/issues/207#issuecomment-2612120009.

Remove Python 2 leftovers

---

.github/workflows/python.yml
.ruff.toml

1. Add ruff configuration.
2. Enforce ruff rules in CI
Item 2 is debatable.
Follow-up of #215.

Enforce ruff rules

---

CONTRIBUTING.md
pom.xml

Fixes #107.
The changes to `CONTRIBUTING.md` should be straightforward, but I'm open to other ways to update `pom.xml`. There doesn't appear to be an equivalent to `mailingList` for specifying a forum, so I opted to just remove the `mailingLists` block to minimize confusion. If keeping the archive links only or doing something else is preferable, happy to do that instead.

Replace mailing lists and QA with forum.image.sc and Zenodo
